import {StyleSheet} from 'react-native';
//Constants
import {COLORS} from '@Utils/constants';

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    paddingTop: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.white,
  },
  closeContainer: {
    zIndex: 10,
    position: 'absolute',
    right: 20,
    top: 10,
    width: 37,
    height: 37,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.lightGray3,
    borderRadius: 50,
    overflow: 'hidden',
  },
  iconClose: {
    width: '75%',
    height: '75%',
    resizeMode: 'contain',
    tintColor: COLORS.black,
  },
  iconContainer: {
    width: '100%',
    flex: 0.5,
    // backgroundColor: 'red',
    alignSelf: 'center',
  },
  textContainer: {
    width: '100%',
    flex: 0.5,
    justifyContent: 'flex-end',
    alignItems: 'center',
    // backgroundColor: 'yellow',
  },
  mainTitleSub: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerTitle: {
    width: '100%',
    paddingHorizontal: 20,
    height: 'auto',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  containerSubTitle: {
    width: '100%',
    minHeight: 50,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  containerBtn: {
    width: '100%',
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    paddingRight: 25,
    paddingLeft: 25,
  },
  txtTitle: {
    width: '90%',
    height: 'auto',
    fontSize: 35,
    textAlign: 'center',
    fontWeight: 'bold',
    color: COLORS.primary,
    // backgroundColor: 'red',
  },
  txtSubTitle: {
    width: '85%',
    fontSize: 15,
    fontWeight: '300',
    textAlign: 'center',
    color: COLORS.darkgray,
  },
  txtBtn: {
    fontSize: 14,
    textTransform: 'uppercase',
    fontWeight: 'bold',
    color: COLORS.white,
  },
  containerAcceptBtnAcc: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: 50,
    overflow: 'hidden',
  },
  containerAcceptBtnErr: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.red,
    borderRadius: 50,
    overflow: 'hidden',
  },
});
